{% set name = "apache-superset" %}
{% set version = "2.1.0" %}


package:
  name: superset
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-superset-{{ version }}.tar.gz
  sha256: af137dbaea3fae1ec9bc9217a73357eadc152362df92b7f9e26015a52912c524

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - superset = superset.cli.main:superset

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - backoff >=1.8.0
    - bleach >=3.0.2,<4.0.0
    - cachelib >=0.4.1,<0.5
    - celery >=5.2.2,<6.0.0
    - click >=8.0.3
    - colorama
    - croniter >=0.3.28
    - cron-descriptor
    - cryptography >=39.0.1,<40
    - deprecation >=2.1.0,<2.2.0
    - flask >=2.1.3,<2.2
    - flask-appbuilder >=4.3.0,<5.0.0
    - flask-caching >=1.10.1,<1.11
    - flask-compress >=1.13,<2.0
    - flask-talisman >=1.0.0,<2.0
    - flask-login 0.6.0
    - flask-migrate >=3.1.0,<4.0
    - flask-wtf >=1.0.1,<1.1
    - func_timeout
    - geopy
    - graphlib-backport
    - gunicorn >=20.1.0  # [not win]
    - hashids >=1.3.1,<2
    - holidays >=0.17.2,<0.18
    - humanize
    - isodate
    - markdown >=3.0
    - msgpack-python >=1.0.0,<1.1
    - numpy 1.23.5
    - pandas >=1.5.3,<1.6
    - parsedatetime
    - pgsanity
    - polyline
    - pyparsing >=3.0.6,<4
    - python-dateutil
    - python-dotenv
    - python-geohash
    - pyarrow >=10.0.1,<11
    - pyyaml >=5.4
    - PyJWT >=2.4.0,<3.0
    - redis-py
    - selenium >=3.141.0
    - sshtunnel >=0.4.0,<0.5
    - simplejson >=3.15.0
    - slack-sdk >=3.1.1,<4
    - sqlalchemy >=1.4,<2
    - sqlalchemy-utils >=0.38.3,<0.39
    - sqlparse >=0.4.3,<0.5
    - tabulate >=0.8.9,<0.9
    - typing-extensions >=4,<5
    - waitress  # [win]
    - wtforms >=2.3.3,<2.4
    - wtforms-json
    - xlsxwriter >=3.0.7,<3.1

test:
  imports:
    - superset
    - superset.cli
  requires:
    # for some reason pip check fails since something needs the pip typing package, so just install it
    - typing
  commands:
    - pip check
    - superset --help
  requires:
    - pip

about:
  summary: A modern, enterprise-ready business intelligence web application
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: https://superset.apache.org
  doc_url: https://superset.apache.org
  dev_url: https://github.com/apache/superset

extra:
  recipe-maintainers:
    - mariusvniekerk
    - sodre
    - CurtLH
    - xmnlab
