{% set name = "apache-superset" %}
{% set version = "4.1.1" %}

package:
  name: superset
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache-superset-{{ version }}.tar.gz
  sha256: eda17db9adfb3d1c3135e473adacea042cc05d0125f8cbb577ab81175f548ef8

build:
  skip: true  # [py<39]
  entry_points:
    - superset=superset.cli.main:superset
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - backoff >=1.8.0
    - celery >=5.3.6, <6.0.0
    - click >=8.0.3
    - click-option-group
    - colorama
    - croniter >=0.3.28
    - cron-descriptor
    - cryptography >=42.0.4, <43.0.0
    - deprecation >=2.1.0, <2.2.0
    - flask >=2.2.5, <3.0.0
    - flask-appbuilder >=4.5.0, <5.0.0
    - flask-caching >=2.1.0, <3
    - flask-compress >=1.13, <2.0
    - flask-talisman >=1.0.0, <2.0
    - flask-login >=0.6.0, < 1.0
    - flask-migrate >=3.1.0, <4.0
    - flask-session >=0.4.0, <1.0
    - flask-wtf> =1.1.0, <2.0
    - func_timeout
    - geopy
    - gunicorn >=22.0.0 # [not win]
    - hashids >=1.3.1, <2
    - holidays >=0.25, <0.26
    - humanize
    - importlib_metadata
    - isodate
    - jsonpath-ng >=1.6.1, <2
    - Mako >=1.2.2
    - markdown >=3.0
    - msgpack >=1.0.0, <1.1
    - nh3 >=0.2.11, <0.3
    - numpy ==1.23.5
    - packaging
    - pandas >=2.0.3, <2.1 #pandas[performance] >=2.0.3, <2.1
    - parsedatetime
    - paramiko >=3.4.0
    - pgsanity
    - polyline >=2.0.0, <3.0
    - pyparsing >=3.0.6, <4
    - python-dateutil
    - python-dotenv
    - python-geohash
    - pyarrow >=14.0.1, <15
    - pyyaml >=6.0.0, <7.0.0
    - PyJWT >=2.4.0, <3.0
    - redis-py >=4.6.0, <5.0
    - selenium >=3.141.0, <4.10.0
    - shillelagh >=1.2.18, <2.0 #shillelagh[gsheetsapi]>=1.2.18, <2.0
    - shortid
    - sshtunnel >=0.4.0, <0.5
    - simplejson >=3.15.0
    - slack_sdk >=3.19.0, <4
    - sqlalchemy >=1.4, <2
    - sqlalchemy-utils >=0.38.3, <0.39
    - sqlglot >=25.24.0,<26
    - sqlparse >=0.5.0
    - tabulate >=0.8.9, <0.9
    - typing-extensions >=4, <5
    # - waitress; sys_platform == 'win32'",
    - wtforms >=2.3.3, <4
    - wtforms-json
    - xlsxwriter >=3.0.7, <3.1

test:
  imports:
    - superset
    - superset.cli
  commands:
    - pip check
    - superset --help
  requires:
    - pip

about:
  home: https://superset.apache.org/
  summary: A modern, enterprise-ready business intelligence web application
  license: OGC-1.0 AND Apache-2.0
  license_file:
    - NOTICE
    - LICENSE.txt

extra:
  recipe-maintainers:
    - mariusvniekerk
    - sodre
    - CurtLH
    - xmnlab
    - mediocretech
