{% set name = "apache-superset" %}
{% set version = "0.38.0" %}


package:
  name: superset
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-superset-{{ version }}.tar.gz
  sha256: 99921de450de0f7857cc3cae566e8ce96f2b4e4845291609728b121f2173c4cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - superset = superset.cli:superset

requirements:
  host:
    - pip
    - python >=3.6,<3.7
  run:
    - backoff >=1.8.0
    - bleach >=3.0.2,<4.0.0
    - cachelib >=0.1.1,<0.2
    - celery >=4.3.0,<5.0.0,!=4.4.1
    - click <8
    - colorama
    - contextlib2
    - croniter >=0.3.28
    - cryptography >=2.4.2
    - dataclasses <0.7
    - flask >=1.1.0,<2.0.0
    - flask-appbuilder >=3.0.1,<4.0.0
    - flask-caching
    - flask-compress
    - flask-migrate
    - flask-talisman
    - flask-wtf
    - geopy
    - gunicorn >=20.0.2,<20.1
    - humanize
    - isodate
    - markdown >=3.0
    - msgpack-python >=1.0.0,<1.1
    - pandas >=1.0.3,<1.1
    - parsedatetime
    - pathlib2
    - polyline
    - pyarrow >=0.17.0,<0.18
    - python >=3.6,<3.7
    - python-dateutil
    - python-dotenv
    - python-geohash
    - pyyaml >=5.1
    - retry >=0.9.2
    - selenium >=3.141.0
    - simplejson >=3.15.0
    - slackclient ==2.5.0
    - sqlalchemy >=1.3.16,<2.0
    - sqlalchemy-utils >=0.36.6,<0.37
    - sqlparse ==0.3.0
    - typing
    - wtforms-json

test:
  imports:
    - superset
    - superset.cli
  commands:
    # for some reason pip check fails since something needs the pip typing package, so just install it
    - pip install typing
    - pip check
    - superset --help
    # - export SUPERSET_HOME={{ PREFIX }}  # [unix]
    # - set SUPERSET_HOME={{ PREFIX }}  # [win]
    # - superset db upgrade
    # - export FLASK_APP='superset'
    # - flask fab create-admin
    #     --username admin
    #     --firstname admin
    #     --lastname admin
    #     --email admin@fab.org
    #     --password admin
    # - superset load_examples
    # - superset init
  requires:
    - pip

about:
  summary: A modern, enterprise-ready business intelligence web application
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: https://superset.apache.org
  doc_url: https://superset.apache.org
  dev_url: https://github.com/apache/superset


extra:
  recipe-maintainers:
    - mariusvniekerk
    - sodre
    - CurtLH
