{% set name = "apache-superset" %}
{% set version = "2.0.0" %}


package:
  name: superset
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-superset-{{ version }}.tar.gz
  sha256: a29d2cec1eb10107593d3e890f1044b3ea554fcf7fbeb924f748bc8b4d56f7d8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - superset = superset.cli.main:superset

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - backoff >=1.8.0
    - bleach >=3.0.2,<4.0.0
    - cachelib >=0.4.1,<0.5
    - celery >=5.2.2,<6.0.0
    - click >=8.0.3
    - colorama
    - cron-descriptor
    - croniter >=0.3.28
    - cryptography >=3.3.2
    - deprecation >=2.1.0,<2.2.0
    # see: https://github.com/apache/superset/issues/20723
    - flask >=2.0.0,<2.2.0
    - flask-appbuilder >=4.1.3,<5.0.0
    - flask-caching >=1.10.0
    - flask-compress
    - flask-migrate
    - flask-talisman
    - flask-wtf
    - func_timeout
    - geopy
    - graphlib-backport
    - gunicorn >=20.1.0
    - hashids >=1.3.1,<2
    # https://github.com/dr-prodigy/python-holidays/issues/406
    - holidays 0.10.3
    - humanize
    - isodate
    - markdown >=3.0
    - msgpack-python >=1.0.0,<1.1
    - numpy 1.22.1
    - pandas >=1.3.0,<1.4
    - parsedatetime
    - pgsanity
    - polyline
    - pyarrow >=5.0.0,<6.0
    - pyjwt >=2.4.0,<3.0
    - pyparsing >=3.0.6,<4
    - python >=3.8,<3.10
    - python-dateutil
    - python-dotenv
    - python-geohash
    - pyyaml >=5.4
    - redis-py
    - selenium >=3.141.0
    - simplejson >=3.15.0
    # slack changes file upload api in the future versions
    - slackclient 2.5.0
    - sqlalchemy >=1.3.16,<1.4,!=1.3.21
    - sqlalchemy-utils >=0.37.8,<0.38
    - sqloxide 0.1.15
    # see https://github.com/andialbrecht/sqlparse/issues/562
    - sqlparse 0.3.0
    - tabulate 0.8.9
    # needed to support Literal (3.8) and TypeGuard (3.10)
    - typing_extensions >=3.10,<4
    # see: https://github.com/apache/superset/issues/20723
    - werkzeug 2.0.3
    - wtforms-json

test:
  imports:
    - superset
    - superset.cli
  requires:
    # for some reason pip check fails since something needs the pip typing package, so just install it
    - typing
  commands:
    - pip check
    - superset --help
  requires:
    - pip

about:
  summary: A modern, enterprise-ready business intelligence web application
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: https://superset.apache.org
  doc_url: https://superset.apache.org
  dev_url: https://github.com/apache/superset

extra:
  recipe-maintainers:
    - mariusvniekerk
    - sodre
    - CurtLH
    - xmnlab
