{% set name = "apache-superset" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-superset-{{ version }}.tar.gz
  sha256: af137dbaea3fae1ec9bc9217a73357eadc152362df92b7f9e26015a52912c524

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - superset = superset.cli.main:superset

requirements:
  host:
    - pip
    - python >=3.7,<=3.11
  run:
    - python >=3.7,<=3.11  
    - backoff >=1.8.0
    - bleach >=3.0.2,<4.0.0
    - cachelib >=0.4.1,<0.5
    - celery >=5.2.2,<6.0.0
#    - cffi >=1.15.1
    - click >=8.0.3
    - colorama
    - croniter >=0.3.28
    - cron-descriptor
    - cryptography >=3.3.2,<40
    - deprecation >=2.1.0,<2.2.0
    # see: https://github.com/apache/superset/issues/20723
    - flask >=2.0.0,<3.0.0
    - flask-appbuilder >=4.1.3,<5.0.0
    - flask-caching >=1.10.1,<1.11
    - flask-compress >=1.13,<2.0
    - flask-talisman >=1.0.0,<2.0
    - flask-login ==0.6.0
    - flask-migrate >=3.1.0,<4.0
    - flask-wtf >=1.0.1,<1.1
    - func_timeout
    - geopy
    - graphlib-backport
    - hashids >=1.3.1,<2
    - holidays >=0.17.2,<0.18
    - humanize
    - isodate
    - markdown >=3.0
    - msgpack-python >=1.0.0,<1.1
    - numpy ==1.23.5
    - pandas >=1.3.0,<1.6
    - parsedatetime
    - pgsanity
    - polyline
    - pyparsing >=3.0.6,<4
    - python-dateutil
    - python-dotenv
    - python-geohash
    - pyarrow >=5.0.0,<11
    - pyyaml >=5.4
    - pyjwt >=2.4.0,<3.0
    - redis-py
    - selenium >=3.141.0
    - sshtunnel >=0.4.0,<0.5
    - simplejson >=3.15.0
    - slack_sdk >=3.1.1,<4
    - sqlalchemy >=1.3.16,<2,!=1.3.21
    - sqlalchemy-utils >=0.37.8,<0.39
#    - sqloxide 0.1.15
    # see https://github.com/andialbrecht/sqlparse/issues/562
    - sqlparse >=0.4.3,<0.5
    - tabulate ==0.8.9
    # needed to support Literal (3.8) and TypeGuard (3.10)
    - typing-extensions >=3.10,<5
    # see: https://github.com/apache/superset/issues/20723
    - werkzeug >=2.3.3,<3
    - wtforms >=2.3.3,<2.4
    - wtforms-json
    - xlsxwriter >=3.0.7,<3.1
    - gunicorn >=20.1.0  # [not win]
    - waitress  # [win]
    # Keep the package noarch but allow for the osx only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - superset
    - superset.cli
  requires:
    # for some reason pip check fails since something needs the pip typing package, so just install it
    - typing
  commands:
    - pip check
    - superset --help
  requires:
    - pip

about:
  summary: A modern, enterprise-ready business intelligence web application
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: https://superset.apache.org
  doc_url: https://superset.apache.org
  dev_url: https://github.com/apache/superset

extra:
  recipe-maintainers:
    - mariusvniekerk
    - sodre
    - CurtLH
    - xmnlab
