{% set name = "apache-superset" %}
{% set version = "1.4.1" %}


package:
  name: superset
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-superset-{{ version }}.tar.gz
  sha256: 11e3cde45a033e020f5f8605b53978efca8a4f3c9fb71264183f9fd9de238e23

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - superset = superset.cli:superset

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    # - alembic
    # - apispec
    - backoff >=1.8.0
    - bleach >=3.0.2
    - cachelib >=0.1.1
    - celery >=4.3.0
    - click <8
    - colorama
    - cron-descriptor
    - croniter >=0.3.28
    - cryptography >=3.3.2
    - deprecation >=2.1.0
    - flask >=1.1.0
    - flask-appbuilder >=3.4.3
    # - flask-babel
    - flask-caching >=1.10.0
    - flask-compress
    # - flask-jwt-extended
    # - flask-login
    - flask-migrate
    # - flask-sqlalchemy
    - flask-talisman
    - flask-wtf
    - geopy
    - graphlib-backport
    - gunicorn >=20.1.0
    - holidays 0.10.3
    - humanize
    - isodate
    # note: https://serverfault.com/a/1094095
    - itsdangerous >=1.0.0,<2.0.0
    - markdown >=3.0
    # note: cannot import name 'soft_unicode' from 'markupsafe'
    - markupsafe <=2.0.1
    # - marshmallow
    # - marshmallow-enum
    - msgpack-python >=1.0.0
    # - numpy
    # note: cannot import name 'STR_NA_VALUES' from 'pandas.io.parsers'
    - pandas >=1.2.2,<1.3
    - parsedatetime
    - pgsanity
    - polyline
    - pyarrow >=4.0.1
    - pyjwt >=1.7.1
    - pyparsing >=2.4.7
    - python >=3.7,<3.10
    - python-dateutil
    - python-dotenv
    - python-geohash
    # - pytz
    - pyyaml >=5.4
    - redis-py
    - requests 2.26.0
    - selenium >=3.141.0
    - simplejson >=3.15.0
    - slackclient 2.5.0
    # note: ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine'
    - sqlalchemy >=1.3.16,<1.4,!=1.3.21
    - sqlalchemy-utils >=0.37.8
    - sqlparse 0.3.0
    - tabulate 0.8.9
    - typing_extensions >=3.10
    # - wtforms
    - wtforms-json

test:
  imports:
    - superset
    - superset.cli
  requires:
    # for some reason pip check fails since something needs the pip typing package, so just install it
    - typing
  commands:
    - pip check
    - superset --help
  requires:
    - pip

about:
  summary: A modern, enterprise-ready business intelligence web application
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  home: https://superset.apache.org
  doc_url: https://superset.apache.org
  dev_url: https://github.com/apache/superset

extra:
  recipe-maintainers:
    - mariusvniekerk
    - sodre
    - CurtLH
    - xmnlab
