{% set name = "superset" %}
{% set version = "0.35.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/apache/incubator-{{ name }}/archive/{{ version }}.tar.gz
    sha256: 652880a492f650e12c6a903d5a1e02211a7b8b4e9090109a6fa90288bdf1a9ad
  - url: https://raw.githubusercontent.com/apache/incubator-{{ name }}/master/LICENSE.txt
    sha256: 600710369a31face16d98c10682bda5d513fe1136f39f0c12f6f6cd9e2ccfe98
  - patches:
      - replace-scripts-with-console.patch

build:
  #noarch: python
  number: 0
  script:
    {% set console_script=os.sep.join(['superset', 'bin', 'superset']) %}
    - pushd {{ name }}{{os.sep}}assets
    - npm ci
    - npm run build
    - popd
    - mv {{ console_script }} {{ console_script}}.py
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py2k]
  entry_points:
    - superset = superset.bin.superset:cli

requirements:
  build:
    - nodejs
  host:
    - python
    - pip
  run:
    - python >=3.6
    # All dependency comments come from github
    # https://github.com/apache/incubator-superset/blob/0.35.2/setup.py
    #- backoff >=1.8.0,
    - bleach >=3.0.2, <4.0.0,
    - celery >=4.3.0, <5.0.0,
    - click >=6.0, <7.0.0,  # `click`>=7 forces "-" instead of "_"
    - colorama,
    - contextlib2,
    - croniter >=0.3.28,
    - cryptography >=2.4.2,
    - flask >=1.1.0, <2.0.0,
    - flask-appbuilder >=2.1.13, <2.3.0,
    - flask-caching,
    - flask-compress,
    - flask-talisman,
    - flask-migrate,
    - flask-wtf,
    - geopy,
    - gunicorn <19.9.0,  # deprecated
    - humanize,
    - isodate,
    - markdown >=3.0,
    - msgpack-python >=0.6.1, <0.7.0,  # changed from msgpack to msgpack-pyhton
    - pandas >=0.24.2, <0.25.0,
    - parsedatetime,
    - pathlib2,
    - polyline,
    - python-dateutil,
    - python-dotenv,
    - python-geohash,
    - pyarrow >=0.15.1, <0.16.0,
    - pyyaml >=5.1,
    - retry >=0.9.2,
    - selenium >=3.141.0,
    - simplejson >=3.15.0,
    - sqlalchemy >=1.3.5,<2.0,
    - sqlalchemy-utils >=0.33.2,
    - sqlparse >=0.3.0,<0.4,
    - wtforms-json

  run_constrained:
    # BigQuery
    #- pybigquery >=0.4.10
    #- pandas_gbq >=0.10.0

    # CORS
    - flask-cors >=2.0.0

    # Gsheets
    - gsheetsdb >=0.1.9

    # Hive
    - pyhive >=0.6.1
    - tableschema
    - thrift >=0.11.1,<1.0.0

    # MySQL
    - mysqlclient ==1.4.2.post1

    # PostgreSQL
    # DIVERGENCE with setup.py
    # - psycopg2-binary ==2.7.5
    - psycopg2 ==2.7.5

    # Druid
    - pydruid ==0.5.7
    - requests ==2.22.0

    # Presto
    #- pyhive[presto] >=0.4.0

test:
  commands:
    - export SUPERSET_HOME={{PREFIX}}  # [unix]
    - export FLASK_APP='superset'  # [unix]
    - set SUPERSET_HOME={{PREFIX}}  # [win]
    - set FLASK_APP='superset'  # [win]
    - superset --help
    - superset db upgrade
    - superset fab create-admin
        --username admin
        --firstname admin
        --lastname admin
        --email admin@fab.org
        --password admin
    - superset load_examples
    - superset init
  imports:
    - superset

about:
  home: https://superset.incubator.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Apache Superset (incubating) is a modern, enterprise-ready business intelligence web application.'

  doc_url: https://superset.incubator.apache.org
  dev_url: https://github.com/apache/incubating-superset

extra:
  recipe-maintainers:
    - sodre
    - CurtLH
